### ISSUE TITLE
No reload method

### ISSUE THREAD

**Issue by phanirithvij** [benehmb/MediaControllUI#2]
There is no reload method in https://github.com/benehmb/WindowsMediaController project but you are referencing it in https://github.com/benehmb/MediaControllUI/blob/main/ViewModel/MainViewModel.cs#L156

**Comment by benehmb** [comment]
Yes, you are right. That's just a method, which I added into [WindowsMediaController]( https://github.com/benehmb/WindowsMediaController). It has been just for testing purposes until I am able to fix #1.
If you want to use this method, here it is:
```c#
public static void Reload()
{
    var sessionManager = GlobalSystemMediaTransportControlsSessionManager.RequestAsync().GetAwaiter().GetResult();
    SessionsChanged(sessionManager);
}
```
Just insert this methode in the `Main.cs` of [WindowsMediaController]( https://github.com/benehmb/WindowsMediaController) (If you want to, I can make an commit to that)
Honestly, I really didn`t expect someone to use this program. Hope it helps :)
